# TODO: Add more linters
# https://gist.githubusercontent.com/maratori/47a4d00457a92aa426dbd48a18776322/raw/43d6de07ca238a3994737171bd3fe2cd2b769bc0/.golangci.yml

version: "2"

linters:
  default: none
  enable:
    - unused
    - errcheck
    - gocognit
    - gocyclo
    - govet
    - misspell
    - staticcheck
    - whitespace
  exclusions:
    paths:
      - api/ # 生成コードを除外
      - db/
      - service/command/internal/infrastructure/sqlboiler/models
      - service/command/internal/mock/
    rules:
      # テストコード内のフィールドアライメント警告を無視
      - path: _test\.go$
        linters:
          - govet
        text: "fieldalignment: struct with" # 警告メッセージでマッチ

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment # 可読性を優先するため無効化
      settings:
        shadow:
          strict: true
    gocyclo:
      min-complexity: 30
    misspell:
      locale: US

formatters:
  enable:
    - goimports
    - gofmt
